import Link from 'next/link'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: [ 'latin' ] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <nav style={{ 
          width: "100%", 
          background: "teal", 
          fontSize: "24px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}>
          <Link style={{margin: "5px"}} href="/">Home</Link>
          <Link style={{margin: "5px"}} href="/posts">Posts</Link>
          <Link style={{margin: "5px"}} href="/articles">Articles</Link>
        </nav>
        { children }</body>
    </html>
  );
}
